"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import {
    IconArrowLeft,
    IconDashboard,
    IconActivity,
    IconBook,
    IconRocket,
    IconRefresh,
    IconTool
} from "@tabler/icons-react"
import { AdminPasswordGate } from "@/components/admin/AdminPasswordGate"
import { FeatureMap } from "@/components/admin/mission-control/FeatureMap"
import { DocsLibrary } from "@/components/admin/mission-control/DocsLibrary"
import { TriageDashboard } from "@/components/admin/mission-control/TriageDashboard"

// Using local JSON for the manifest and state for now as they are generated by the audit
import FEATURE_MANIFEST from "../../../../../../home/sosu/.gemini/antigravity/brain/39b024dd-cad2-4d4c-b3db-91ae9f709193/FEATURE_MANIFEST.json"

export default function MissionControlPage() {
    const [activeTab, setActiveTab] = useState<'map' | 'docs' | 'triage'>('map')
    const [docs, setDocs] = useState<{ name: string, path: string }[]>([])

    useEffect(() => {
        // In a real app, this might be an API call
        // For now, mapping some known docs
        setDocs([
            { name: "Production Readiness", path: "docs/PRODUCTION_READINESS.md" },
            { name: "Chat Engine Architecture", path: "docs/CHAT_ENGINE.md" },
            { name: "Error Handling Guide", path: "docs/ERROR_HANDLING.md" },
            { name: "UI Redesign assignment", path: "docs/UI_REDESIGN_WORK_ASSIGNMENT.md" },
            { name: "Gacha System Blueprint", path: "docs/TALKIE_CLONE_BLUEPRINT.md" }
        ])
    }, [])

    const handleRelaunchAudit = () => {
        alert("Relaunching system audit... [AntiGravity Command Sent]")
    }

    const handleFixPillar = () => {
        alert("Initializing Pillar Optimization... [AntiGravity Command Sent]")
    }

    return (
        <AdminPasswordGate>
            <div className="min-h-screen bg-rp-base text-rp-text pb-20">
                {/* Header */}
                <header className="sticky top-0 z-10 border-b border-rp-highlight-med bg-rp-base/80 px-6 py-4 backdrop-blur-md">
                    <div className="mx-auto flex max-w-7xl items-center justify-between">
                        <div className="flex items-center gap-4">
                            <Link
                                href="/admin"
                                className="text-rp-subtle hover:text-rp-text flex items-center gap-2 transition-colors"
                            >
                                <IconArrowLeft size={18} />
                                Dashboard
                            </Link>
                            <div className="bg-rp-highlight-med h-6 w-px" />
                            <h1 className="flex items-center gap-2 text-xl font-bold tracking-tight">
                                <IconRocket className="text-rp-rose" size={24} />
                                Mission Control
                            </h1>
                        </div>

                        <div className="flex gap-3">
                            <button
                                onClick={handleRelaunchAudit}
                                className="bg-rp-surface border-rp-highlight-med hover:bg-rp-overlay active:scale-95 flex items-center gap-2 rounded-xl border px-5 py-2.5 text-sm font-bold transition-all"
                            >
                                <IconRefresh size={18} className="text-rp-foam" />
                                Relaunch Audit
                            </button>
                            <button
                                onClick={handleFixPillar}
                                className="bg-rp-iris text-rp-base shadow-rp-iris/20 active:scale-95 flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-black shadow-lg transition-all hover:opacity-90"
                            >
                                <IconTool size={18} />
                                Fix Root Pillar
                            </button>
                        </div>
                    </div>
                </header>

                <main className="mx-auto max-w-7xl p-6">
                    {/* Tabs Navigation */}
                    <div className="mb-10 flex gap-4 overflow-x-auto border-b border-rp-highlight-low pb-px scrollbar-hide">
                        <TabButton
                            active={activeTab === 'map'}
                            onClick={() => setActiveTab('map')}
                            icon={<IconDashboard size={20} />}
                            label="Feature Map"
                        />
                        <TabButton
                            active={activeTab === 'triage'}
                            onClick={() => setActiveTab('triage')}
                            icon={<IconActivity size={20} />}
                            label="Triage Dashboard"
                        />
                        <TabButton
                            active={activeTab === 'docs'}
                            onClick={() => setActiveTab('docs')}
                            icon={<IconBook size={20} />}
                            label="Docs Library"
                        />
                    </div>

                    {/* Content Area */}
                    <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                        {activeTab === 'map' && <FeatureMap manifest={FEATURE_MANIFEST} />}
                        {activeTab === 'triage' && <TriageDashboard />}
                        {activeTab === 'docs' && <DocsLibrary files={docs} />}
                    </div>
                </main>
            </div>
        </AdminPasswordGate>
    )
}

function TabButton({ active, onClick, icon, label }: { active: boolean, onClick: () => void, icon: React.ReactNode, label: string }) {
    return (
        <button
            onClick={onClick}
            className={`flex items-center gap-2.5 whitespace-nowrap px-4 py-4 text-sm font-bold uppercase tracking-widest transition-all ${active
                    ? 'text-rp-iris border-b-2 border-rp-iris'
                    : 'text-rp-muted hover:text-rp-text border-b-2 border-transparent hover:border-rp-muted'
                }`}
        >
            {icon}
            {label}
        </button>
    )
}
